// ══════════════════════════════════════════════════════════
//  NEXUS ARCADE — GAME DATABASE
//  Sources:
//    F = frogiesarcade.net (self-hosted)
//    P = Plexile-exclusive games (unique to ncdsb.netlify.app)
//    E = external well-known sources
// ══════════════════════════════════════════════════════════

const F = 'https://frogiesarcade.net';
const TH = F + '/stuff/games/';  // thumbnail base
const NC = 'https://ncdsb.netlify.app';

// helper for ncdsb thumbnails
const NT = (n) => NC + '/images/games-images/' + n;

window.GAMES = [

  // ─── FEATURED / TRENDING ──────────────────────────────────
  { id:'slope',           title:'Slope',                    cat:'Arcade',      thumb: TH+'slope.jpg',                   src: F+'/stuff/selfhosted/slope/',                            hot:true  },
  { id:'subway',          title:'Subway Surfers',           cat:'Arcade',      thumb: TH+'subway.png',                  src: F+'/cdn/projects/subway-surfers/',                       hot:true  },
  { id:'geodash',         title:'Geometry Dash',            cat:'Arcade',      thumb: TH+'geodash.png',                 src: F+'/stuff/selfhosted/gdlite/',                           hot:true  },
  { id:'run3',            title:'Run 3',                    cat:'Arcade',      thumb: TH+'run3.png',                    src: F+'/stuff/selfhosted/run3/',                             hot:true  },
  { id:'minecraft',       title:'Minecraft',                cat:'Adventure',   thumb: TH+'minecraft.jpg',               src: F+'/stuff/selfhosted/minecraft/tuff/index.html',         hot:true  },
  { id:'cuphead',         title:'Cuphead',                  cat:'Action',      thumb: TH+'cuphead.png',                 src: 'https://geet.in.net/get/cuphead/embed.html',            hot:true  },
  { id:'among-us',        title:'Among Us',                 cat:'Multiplayer', thumb: TH+'ayodiddy.png',                src: F+'/stuff/selfhosted/among-us/',                         hot:true  },
  { id:'buckshot',        title:'Buckshot Roulette',        cat:'Horror',      thumb: TH+'buckshot.jpg',                src: F+'/stuff/selfhosted/buckshot-roulette/',                hot:true  },

  // ─── ARCADE ───────────────────────────────────────────────
  { id:'cookieclicker',   title:'Cookie Clicker',           cat:'Arcade',      thumb: TH+'cookieclicker.png',           src: F+'/cdn/projects/cookie-clicker/index.html'                        },
  { id:'crossyroad',      title:'Crossy Road',              cat:'Arcade',      thumb: TH+'crossyroad.jpeg',             src: F+'/stuff/selfhosted/crossyroad/'                                  },
  { id:'ovo',             title:'OvO',                      cat:'Arcade',      thumb: TH+'ovo.png',                     src: F+'/cdn/projects/ovo/'                                             },
  { id:'monkeymart',      title:'Monkey Mart',              cat:'Arcade',      thumb: TH+'monkey-mart.jpg',             src: F+'/stuff/selfhosted/monkey-mart/'                                 },
  { id:'stickmanhook',    title:'Stickman Hook',            cat:'Arcade',      thumb: TH+'stickmanhook.jpg',            src: F+'/cdn/projects/stickman-hook/'                                   },
  { id:'totm',            title:'Tomb of the Mask',         cat:'Arcade',      thumb: TH+'totm.png',                    src: F+'/stuff/selfhosted/tomb-of-the-mask/'                            },
  { id:'flappybird',      title:'Flappy Bird',              cat:'Arcade',      thumb: TH+'flappybird.png',              src: F+'/stuff/selfhosted/flappy-bird/'                                 },
  { id:'angrybirds',      title:'Angry Birds',              cat:'Arcade',      thumb: TH+'angrybirds.png',              src: F+'/stuff/selfhosted/angry-birds/'                                 },
  { id:'tubejumpers',     title:'Tube Jumpers',             cat:'Arcade',      thumb: TH+'tubejumpers.png',             src: F+'/stuff/selfhosted/tube-jumpers/'                                },
  { id:'burritobison',    title:'Burrito Bison',            cat:'Arcade',      thumb: TH+'burritobison.jpg',            src: F+'/stuff/selfhosted/burrito-bison/'                               },
  { id:'adofai',          title:'A Dance of Fire and Ice',  cat:'Arcade',      thumb: TH+'adofai.png',                  src: F+'/stuff/selfhosted/adofai/'                                      },
  { id:'bloons',          title:'Bloons TD',                cat:'Arcade',      thumb: TH+'bloons.png',                  src: F+'/stuff/selfhosted/btd/'                                         },
  { id:'bloons2',         title:'Bloons TD 2',              cat:'Arcade',      thumb: TH+'bloons2.png',                 src: F+'/stuff/selfhosted/btd2/'                                        },
  { id:'peggle',          title:'Peggle',                   cat:'Arcade',      thumb: TH+'peggle.png',                  src: F+'/stuff/selfhosted/peggle/'                                      },
  { id:'tossturtle',      title:'Toss the Turtle',          cat:'Arcade',      thumb: TH+'tosstheturtle.png',           src: F+'/stuff/selfhosted/toss-the-turtle/'                             },
  { id:'learntofly',      title:'Learn to Fly',             cat:'Arcade',      thumb: TH+'learn2fly.png',               src: F+'/stuff/selfhosted/learn-to-fly/'                                },
  { id:'achievement',     title:'Achievement Unlocked',     cat:'Arcade',      thumb: TH+'au.jpg',                      src: F+'/stuff/selfhosted/achievement-unlocked/'                        },
  { id:'avalanche',       title:'Avalanche',                cat:'Arcade',      thumb: TH+'avalanche.png',               src: F+'/stuff/selfhosted/avalanche/'                                   },
  { id:'dodge',           title:'Dodge',                    cat:'Arcade',      thumb: TH+'dodge.png',                   src: F+'/stuff/selfhosted/dodge/'                                       },
  { id:'rhythmhell',      title:'Rhythm Hell',              cat:'Arcade',      thumb: TH+'rhythmhell.png',              src: F+'/stuff/selfhosted/rhythm-hell/'                                 },
  { id:'blockhop',        title:'Block Blast',              cat:'Arcade',      thumb: TH+'blockblast.png',              src: F+'/stuff/selfhosted/block-blast/'                                 },
  { id:'retroheli',       title:'Retro Helicopter',         cat:'Arcade',      thumb: TH+'retrohellicopter.png',        src: F+'/stuff/selfhosted/retro-helicopter/'                            },
  { id:'rerun',           title:'Re:Run',                   cat:'Arcade',      thumb: TH+'rerun.jpg',                   src: F+'/stuff/selfhosted/rerun/'                                       },
  { id:'wbwwb',           title:'We Become What We Behold', cat:'Arcade',      thumb: TH+'wbwwb.png',                   src: F+'/stuff/selfhosted/wbwwb/'                                       },
  { id:'dnttch',          title:'Do Not Take This Cat Home',cat:'Arcade',      thumb: TH+'dnttch.png',                  src: F+'/stuff/selfhosted/do-not-take-this-cat-home/'                   },
  { id:'badgame',         title:'Bad Game',                 cat:'Arcade',      thumb: TH+'badgame.png',                 src: F+'/stuff/selfhosted/bad-game/'                                    },
  { id:'fused240',        title:'Fused 240',                cat:'Arcade',      thumb: TH+'fused240.jpg',                src: F+'/stuff/selfhosted/fused-240/'                                   },
  { id:'simplelootidle',  title:'Simple Loot Idle',         cat:'Arcade',      thumb: TH+'simplelootidle.png',          src: F+'/stuff/selfhosted/simple-loot-idle/'                            },
  { id:'100pong',         title:'100 Player Pong',          cat:'Arcade',      thumb: TH+'100ng.jpg',                   src: F+'/stuff/selfhosted/100-player-pong/'                             },
  { id:'wbwwb2',          title:'Testimonium',              cat:'Arcade',      thumb: TH+'testimonium.png',             src: F+'/stuff/selfhosted/testimonium/'                                 },
  { id:'superfowlst',     title:'Super Fowlst',             cat:'Arcade',      thumb: TH+'superfowlst.png',             src: F+'/stuff/selfhosted/super-fowlst/'                                },
  { id:'hexgl',           title:'HexGL',                    cat:'Arcade',      thumb: TH+'hexgl.png',                   src: 'https://hexgl.bkcore.com/play/'                                   },

  // ─── ACTION ───────────────────────────────────────────────
  { id:'doom',            title:'Doom',                     cat:'Action',      thumb: TH+'doom.jpg',                    src: F+'/stuff/selfhosted/doom/'                                        },
  { id:'quake',           title:'Quake',                    cat:'Action',      thumb: TH+'quake.jpg',                   src: F+'/stuff/selfhosted/quake/'                                       },
  { id:'halflife',        title:'Half-Life',                cat:'Action',      thumb: TH+'halflife.jpg',                src: F+'/stuff/selfhosted/half-life/'                                   },
  { id:'superhot',        title:'SUPERHOT',                 cat:'Action',      thumb: TH+'superhot.png',                src: F+'/stuff/selfhosted/superhot/'                                    },
  { id:'pizzatower',      title:'Pizza Tower',              cat:'Action',      thumb: TH+'pizzatower.jpg',              src: F+'/stuff/selfhosted/pizza-tower/'                                 },
  { id:'sonicmania',      title:'Sonic Mania',              cat:'Action',      thumb: TH+'sonicmania.jpg',              src: F+'/stuff/selfhosted/sonic-mania/'                                 },
  { id:'sonic1',          title:'Sonic the Hedgehog',       cat:'Action',      thumb: TH+'sonic1.png',                  src: F+'/stuff/selfhosted/sonic1/'                                      },
  { id:'sonic2',          title:'Sonic the Hedgehog 2',     cat:'Action',      thumb: TH+'sonic2.png',                  src: F+'/stuff/selfhosted/sonic2/'                                      },
  { id:'sonic3',          title:'Sonic the Hedgehog 3',     cat:'Action',      thumb: TH+'sonic3.png',                  src: F+'/stuff/selfhosted/sonic3/'                                      },
  { id:'soniccd',         title:'Sonic CD',                 cat:'Action',      thumb: TH+'soniccd.png',                 src: F+'/stuff/selfhosted/soniccd/'                                     },
  { id:'clusterrush',     title:'Cluster Rush',             cat:'Action',      thumb: NT('clusterrush.png'),            src: 'https://geet.in.net/get/cluster-rush/game.html',        hot:true  },
  { id:'karlson',         title:'Karlson 2D',               cat:'Action',      thumb: TH+'karlson.png',                 src: F+'/stuff/selfhosted/karlson-2d/'                                  },
  { id:'gta2',            title:'GTA 2',                    cat:'Action',      thumb: TH+'gta2.png',                    src: F+'/stuff/selfhosted/gta2/'                                        },
  { id:'spiderman',       title:'Spider-Man',               cat:'Action',      thumb: TH+'spiderman.jpg',               src: F+'/stuff/selfhosted/spiderman/'                                   },
  { id:'happywheels',     title:'Happy Wheels',             cat:'Action',      thumb: TH+'happywheels.jpg',             src: 'https://www.miniplay.com/embed/happy-wheels'                      },
  { id:'gunmayhem',       title:'Gun Mayhem',               cat:'Action',      thumb: TH+'gun-mayhem.png',              src: F+'/stuff/selfhosted/gun-mayhem/'                                  },
  { id:'gunmayhem2',      title:'Gun Mayhem 2',             cat:'Action',      thumb: TH+'gun-mayhem2.jpg',             src: F+'/stuff/selfhosted/gun-mayhem-2/'                                },
  { id:'getaway',         title:'Getaway Shootout',         cat:'Action',      thumb: TH+'getaway-shootout.png',        src: F+'/stuff/selfhosted/getaway-shootout/'                            },
  { id:'rooftop1',        title:'Rooftop Snipers',          cat:'Action',      thumb: TH+'rooftop-snipers.jpg',         src: F+'/stuff/selfhosted/rooftop-snipers/'                             },
  { id:'rooftop2',        title:'Rooftop Snipers 2',        cat:'Action',      thumb: TH+'rooftop-snipers2.jpg',        src: F+'/stuff/selfhosted/rooftop-snipers-2/'                           },
  { id:'10mtd',           title:'10 Minutes Till Dawn',     cat:'Action',      thumb: TH+'10mtd.png',                   src: F+'/stuff/selfhosted/10-minutes-till-dawn/'                        },
  { id:'alien',           title:'Alien Hominid',            cat:'Action',      thumb: TH+'alien.png',                   src: F+'/stuff/selfhosted/alien-hominid/'                               },
  { id:'baconmaydie',     title:'Bacon May Die',            cat:'Action',      thumb: TH+'baconmaydie.jpg',             src: F+'/stuff/selfhosted/bacon-may-die/'                               },
  { id:'ragdollarchers',  title:'Ragdoll Archers',          cat:'Action',      thumb: TH+'ragdollarchers.jpg',          src: F+'/stuff/selfhosted/ragdoll-archers/'                             },
  { id:'ragdollhit',      title:'Ragdoll Hit',              cat:'Action',      thumb: TH+'ragdoll.png',                 src: F+'/stuff/selfhosted/ragdoll-hit/'                                 },
  { id:'venge',           title:'Venge.io',                 cat:'Action',      thumb: TH+'venge.jpg',                   src: 'https://venge.io'                                                 },
  { id:'evio',            title:'ev.io',                    cat:'Action',      thumb: TH+'evio.png',                    src: 'https://ev.io'                                                    },
  { id:'gorilla',         title:'Gorilla Tag',              cat:'Action',      thumb: TH+'thetag.png',                  src: F+'/stuff/selfhosted/gorilla-tag/'                                 },
  { id:'crashbandi',      title:'Crash Bandicoot',          cat:'Action',      thumb: TH+'crashbandi.png',              src: F+'/stuff/selfhosted/crash-bandicoot/'                             },
  { id:'nzp',             title:'Nazi Zombies Portable',    cat:'Action',      thumb: TH+'nzp.png',                     src: 'https://nzp.gay/'                                                 },

  // ─── HORROR ───────────────────────────────────────────────
  { id:'fnaf1',           title:'FNAF 1',                   cat:'Horror',      thumb: TH+'fnaf1.png',                   src: F+'/stuff/selfhosted/fnaf/'                                        },
  { id:'fnaf2',           title:'FNAF 2',                   cat:'Horror',      thumb: TH+'fnaf2.png',                   src: F+'/stuff/selfhosted/fnaf2/'                                       },
  { id:'fnaf3',           title:'FNAF 3',                   cat:'Horror',      thumb: TH+'fnaf3.png',                   src: F+'/stuff/selfhosted/fnaf3/'                                       },
  { id:'fnaf4',           title:'FNAF 4',                   cat:'Horror',      thumb: TH+'fnaf4.png',                   src: F+'/stuff/selfhosted/fnaf4/'                                       },
  { id:'fnaf5',           title:'FNAF Sister Location',     cat:'Horror',      thumb: TH+'fnafsl.jpg',                  src: F+'/stuff/selfhosted/fnaf5/'                                       },
  { id:'fnaf6',           title:'Pizzeria Simulator',       cat:'Horror',      thumb: TH+'pizzeriasimulator.png',       src: F+'/stuff/selfhosted/fnaf6/'                                       },
  { id:'fnafworld',       title:'FNAF World',               cat:'Horror',      thumb: TH+'fnafworld.png',               src: F+'/stuff/selfhosted/fnaf-world/'                                  },
  { id:'ucn',             title:'Ultimate Custom Night',    cat:'Horror',      thumb: TH+'ucn.jpg',                     src: F+'/stuff/selfhosted/ucn/'                                         },
  { id:'fnaw',            title:"Five Nights at Winston's", cat:'Horror',      thumb: TH+'fnaw.jpg',                    src: F+'/stuff/selfhosted/fnaw/'                                        },
  { id:'fnae',            title:"Five Nights at Epsteins",  cat:'Horror',      thumb: TH+'fnae.png',                    src: F+'/stuff/selfhosted/fnae/'                                        },
  { id:'baldi',           title:"Baldi's Basics",           cat:'Horror',      thumb: TH+'baldi.png',                   src: F+'/stuff/selfhosted/baldis-basics/'                               },
  { id:'baf',             title:'Burger and Frights',       cat:'Horror',      thumb: TH+'baf.png',                     src: F+'/cdn/projects/burger-and-frights/index.html'                    },
  { id:'repo',            title:'R.E.P.O.',                 cat:'Horror',      thumb: TH+'repo.png',                    src: F+'/stuff/selfhosted/repo/'                                        },
  { id:'raldi',           title:"Raldi's Crackhouse",       cat:'Horror',      thumb: TH+'raldi.png',                   src: F+'/stuff/selfhosted/raldi/'                                       },
  { id:'batim',           title:'Bendy and the Ink Machine',cat:'Horror',      thumb: TH+'batim.png',                   src: F+'/stuff/selfhosted/batim/'                                       },

  // ─── ADVENTURE ────────────────────────────────────────────
  { id:'hollowknight',    title:'Hollow Knight',            cat:'Adventure',   thumb: TH+'hollow.png',                  src: F+'/stuff/selfhosted/hollow-knight/'                               },
  { id:'terraria',        title:'Terraria',                 cat:'Adventure',   thumb: TH+'terraria.png',                src: F+'/stuff/selfhosted/terraria/'                                    },
  { id:'omori',           title:'OMORI',                    cat:'Adventure',   thumb: TH+'omori.png',                   src: F+'/stuff/selfhosted/omori/'                                       },
  { id:'danganronpa',     title:'Danganronpa',              cat:'Adventure',   thumb: TH+'danganronpa.png',             src: F+'/stuff/selfhosted/danganronpa/'                                 },
  { id:'sm64',            title:'Super Mario 64',           cat:'Adventure',   thumb: TH+'sm64.png',                    src: F+'/stuff/selfhosted/sm64/'                                        },
  { id:'smw',             title:'Super Mario World',        cat:'Adventure',   thumb: TH+'smw.png',                     src: F+'/stuff/selfhosted/smw/'                                         },
  { id:'smb',             title:'Super Mario Bros',         cat:'Adventure',   thumb: TH+'smb.png',                     src: F+'/stuff/selfhosted/smb/'                                         },
  { id:'smas',            title:'Super Mario All Stars',    cat:'Adventure',   thumb: TH+'smas.png',                    src: F+'/stuff/selfhosted/smas/'                                        },
  { id:'smbd',            title:'Super Mario Bros Deluxe',  cat:'Adventure',   thumb: TH+'smbd.jpg',                   src: F+'/stuff/selfhosted/smbd/'                                        },
  { id:'sma2',            title:'Super Mario Advance 2',    cat:'Adventure',   thumb: TH+'sma2.png',                    src: F+'/stuff/selfhosted/sma2/'                                        },
  { id:'sma4',            title:'Super Mario Advance 4',    cat:'Adventure',   thumb: TH+'sma4.png',                    src: F+'/stuff/selfhosted/sma4/'                                        },
  { id:'nsmb',            title:'New Super Mario Bros DS',  cat:'Adventure',   thumb: TH+'nsmb.png',                    src: F+'/stuff/selfhosted/nsmb/'                                        },
  { id:'zelda-oot',       title:"Zelda: Ocarina of Time",   cat:'Adventure',   thumb: TH+'lozoft.jpg',                  src: F+'/stuff/selfhosted/zelda-oot/'                                   },
  { id:'zelda-ladx',      title:"Zelda: Link's Awakening",  cat:'Adventure',   thumb: TH+'lozladx.png',                 src: F+'/stuff/selfhosted/zelda-ladx/'                                  },
  { id:'pokemonfr',       title:'Pokémon FireRed',          cat:'Adventure',   thumb: TH+'pokemonfirered.jpg',          src: F+'/stuff/selfhosted/pokemon-firered/'                             },
  { id:'pokemonplat',     title:'Pokémon Platinum',         cat:'Adventure',   thumb: TH+'ppv.png',                     src: F+'/stuff/selfhosted/pokemon-platinum/'                            },
  { id:'acww',            title:'Animal Crossing Wild World',cat:'Adventure',  thumb: TH+'acww.jpg',                   src: F+'/stuff/selfhosted/acww/'                                        },
  { id:'banjo',           title:'Banjo-Kazooie',            cat:'Adventure',   thumb: TH+'banjo.jpg',                   src: F+'/stuff/selfhosted/banjo-kazooie/'                               },
  { id:'southpark64',     title:'South Park 64',            cat:'Adventure',   thumb: TH+'southpark.jpg',               src: F+'/stuff/selfhosted/south-park-64/'                               },
  { id:'portal',          title:'Portal: Flash Version',    cat:'Adventure',   thumb: TH+'portal.png',                  src: F+'/stuff/selfhosted/portal/'                                      },
  { id:'redball4',        title:'Red Ball 4',               cat:'Adventure',   thumb: TH+'redball4.png',                src: F+'/stuff/selfhosted/red-ball-4/'                                  },
  { id:'diggy',           title:'Diggy',                    cat:'Adventure',   thumb: TH+'diggy.png',                   src: F+'/stuff/selfhosted/diggy/'                                       },
  { id:'btts',            title:'Big Tower Tiny Square',    cat:'Adventure',   thumb: TH+'btts.png',                    src: F+'/stuff/selfhosted/big-tower-tiny-square/'                       },
  { id:'sfpa',            title:'Super Fancy Pants',        cat:'Adventure',   thumb: TH+'sfpa.jpg',                    src: F+'/stuff/selfhosted/super-fancy-pants/'                           },
  { id:'raft',            title:'Raft',                     cat:'Adventure',   thumb: TH+'raft.png',                    src: F+'/stuff/selfhosted/raft/'                                        },
  { id:'btr2',            title:'Bob the Robber 2',         cat:'Adventure',   thumb: TH+'btr2.png',                    src: F+'/stuff/selfhosted/bob-the-robber-2/'                            },
  { id:'crashbandi2',     title:'Crash Bandicoot',          cat:'Adventure',   thumb: TH+'crashbandi.png',              src: F+'/stuff/selfhosted/crash-bandicoot/'                             },
  { id:'gorillaftag',     title:'Gorilla Tag',              cat:'Adventure',   thumb: TH+'thetag.png',                  src: F+'/stuff/selfhosted/gorilla-tag/'                                 },
  { id:'slimerancher',    title:'Slime Rancher',            cat:'Adventure',   thumb: TH+'slimerancher.png',            src: F+'/stuff/selfhosted/slime-rancher/'                               },

  // ─── RACING ───────────────────────────────────────────────
  { id:'motox3m',         title:'Moto X3M',                 cat:'Racing',      thumb: TH+'motox3m.jpg',                 src: F+'/stuff/selfhosted/motox3m/'                                     },
  { id:'drivemad',        title:'Drive Mad',                cat:'Racing',      thumb: TH+'drive-mad.png',               src: F+'/stuff/selfhosted/drive-mad/'                                   },
  { id:'driftboss',       title:'Drift Boss',               cat:'Racing',      thumb: TH+'driftboss.png',               src: F+'/stuff/selfhosted/drift-boss/'                                  },
  { id:'polytrack',       title:'Polytrack',                cat:'Racing',      thumb: TH+'polytrack.jpg',               src: F+'/stuff/selfhosted/polytrack/'                                   },
  { id:'slowroads',       title:'Slow Roads',               cat:'Racing',      thumb: TH+'slowroads.png',               src: 'https://slowroads.io'                                             },
  { id:'tanuki',          title:'Tanuki Sunset',            cat:'Racing',      thumb: TH+'tanuki.jpg',                  src: F+'/stuff/selfhosted/tanuki-sunset/'                               },
  { id:'mariokartds',     title:'Mario Kart DS',            cat:'Racing',      thumb: TH+'mkds.png',                    src: F+'/stuff/selfhosted/mario-kart-ds/'                               },
  { id:'adventuredrv',    title:'Adventure Drivers',        cat:'Racing',      thumb: TH+'adventuredrivers.png',        src: F+'/stuff/selfhosted/adventure-drivers/'                           },
  { id:'endlesstruck',    title:'Endless Truck',            cat:'Racing',      thumb: TH+'endlesstruck.png',            src: F+'/stuff/selfhosted/endless-truck/'                               },
  { id:'monstertracks',   title:'Monster Tracks',           cat:'Racing',      thumb: TH+'monster-tracks.png',          src: F+'/stuff/selfhosted/monster-tracks/'                              },
  { id:'bloodmoney',      title:'Blood Money',              cat:'Racing',      thumb: TH+'bloodmoney.png',              src: F+'/stuff/selfhosted/blood-money/'                                 },

  // ─── SPORTS ───────────────────────────────────────────────
  { id:'retrobowl',       title:'Retro Bowl',               cat:'Sports',      thumb: TH+'retrobowl.png',               src: F+'/stuff/selfhosted/retro-bowl/',                       hot:true  },
  { id:'basketrandom',    title:'Basket Random',            cat:'Sports',      thumb: TH+'basketrandom.png',            src: F+'/stuff/selfhosted/basket-random/'                               },
  { id:'aswc',            title:'A Small World Cup',        cat:'Sports',      thumb: TH+'aswc.png',                    src: F+'/stuff/selfhosted/asmallworldcup/'                              },
  { id:'soccerrandom',    title:'Soccer Random',            cat:'Sports',      thumb: TH+'soccerrandom.jpg',            src: F+'/stuff/selfhosted/soccer-random/'                               },
  { id:'basketbros',      title:'Basket Bros',              cat:'Sports',      thumb: TH+'basket-bros.png',             src: F+'/stuff/selfhosted/basket-bros/'                                 },
  { id:'basketstars',     title:'Basketball Stars',         cat:'Sports',      thumb: TH+'basketball-stars.png',        src: F+'/stuff/selfhosted/basketball-stars/'                            },
  { id:'boxingrandom',    title:'Boxing Random',            cat:'Sports',      thumb: TH+'boxingrandom.png',            src: F+'/stuff/selfhosted/boxing-random/'                               },
  { id:'volleyrandom',    title:'Volley Random',            cat:'Sports',      thumb: TH+'volleyrandom.png',            src: F+'/stuff/selfhosted/volley-random/'                               },
  { id:'bouncybball',     title:'Bouncy Basketball',        cat:'Sports',      thumb: TH+'bouncybasketball.png',        src: F+'/stuff/selfhosted/bouncy-basketball/'                           },
  { id:'cannonbball4',    title:'Cannon Basketball 4',      cat:'Sports',      thumb: TH+'cannonbasketball4.jpg',       src: F+'/stuff/selfhosted/cannon-basketball-4/'                         },
  { id:'1on1soccer',      title:'1 on 1 Soccer',            cat:'Sports',      thumb: TH+'1on1soccer.png',              src: F+'/stuff/selfhosted/1on1-soccer/'                                 },

  // ─── SIMULATION ───────────────────────────────────────────
  { id:'bitlife',         title:'BitLife',                  cat:'Simulation',  thumb: TH+'bitlife.jpg',                 src: F+'/stuff/selfhosted/bitlife/'                                     },
  { id:'ppg',             title:'People Playground',        cat:'Simulation',  thumb: TH+'ppg.png',                     src: F+'/stuff/selfhosted/ppgbog/'                                      },
  { id:'balatro',         title:'Balatro',                  cat:'Simulation',  thumb: TH+'balatro.jpg',                 src: F+'/stuff/selfhosted/balatro/'                                     },
  { id:'papas',           title:"Papa's Pizzeria",          cat:'Simulation',  thumb: TH+'papas.png',                   src: F+'/stuff/selfhosted/papas-pizzeria/'                              },
  { id:'cookingmama',     title:'Cooking Mama',             cat:'Simulation',  thumb: TH+'cookingmama.png',             src: F+'/stuff/selfhosted/cooking-mama/'                                },
  { id:'cookingmama2',    title:'Cooking Mama 2',           cat:'Simulation',  thumb: TH+'cookingmama2.png',            src: F+'/stuff/selfhosted/cooking-mama-2/'                              },
  { id:'cookingmama3',    title:'Cooking Mama 3',           cat:'Simulation',  thumb: TH+'cookingmama3.png',            src: F+'/stuff/selfhosted/cooking-mama-3/'                              },
  { id:'advancewars',     title:'Advance Wars',             cat:'Simulation',  thumb: TH+'advancewars.jpg',             src: F+'/stuff/selfhosted/advance-wars/'                                },
  { id:'vibribbon',       title:'Vib-Ribbon',               cat:'Simulation',  thumb: TH+'vib-ribbon.jpg',              src: F+'/stuff/selfhosted/vib-ribbon/'                                  },
  { id:'uno',             title:'UNO',                      cat:'Simulation',  thumb: TH+'uno.png',                     src: F+'/stuff/selfhosted/uno/'                                         },

  // ─── MULTIPLAYER ──────────────────────────────────────────
  { id:'skribbl',         title:'Skribbl.io',               cat:'Multiplayer', thumb: TH+'skribbl.png',                 src: 'https://skribbl.io'                                               },
  { id:'zombsroyale',     title:'Zombs Royale',             cat:'Multiplayer', thumb: TH+'zombs.png',                   src: 'https://zombsroyale.io'                                           },
  { id:'slither',         title:'Slither.io',               cat:'Multiplayer', thumb: TH+'slither.jpg',                 src: 'https://slither.io'                                               },
  { id:'tag',             title:'Tag',                      cat:'Multiplayer', thumb: TH+'tag.png',                     src: F+'/stuff/selfhosted/tag/'                                         },

  // ════════════════════════════════════════════════════════════
  // ─── PLEXILE EXCLUSIVE (not on frogiesarcade) ──────────────
  // ════════════════════════════════════════════════════════════

  { id:'leveldevil',      title:'Level Devil',              cat:'Arcade',      thumb: NT('leveldevil.png'),             src: 'https://level-devil.com',                               hot:true  },
  { id:'snowrider3d',     title:'Snow Rider 3D',            cat:'Racing',      thumb: NT('snowrider3d.png'),            src: 'https://snow-rider-3d.com',                             hot:true  },
  { id:'infinitecraft',   title:'Infinite Craft',           cat:'Simulation',  thumb: NT('infinitecraft.png'),          src: 'https://neal.fun/infinite-craft/',                      hot:true  },
  { id:'1v1lol',          title:'1v1.LOL',                  cat:'Action',      thumb: NT('1v1.lol.png'),                src: 'https://1v1.lol',                                       hot:true  },
  { id:'tunnelrush',      title:'Tunnel Rush',              cat:'Arcade',      thumb: NT('tunnelrush.png'),             src: 'https://tunnel-rush.io',                                hot:true  },
  { id:'deathrun3d',      title:'Death Run 3D',             cat:'Arcade',      thumb: NT('deathrun3d.png'),             src: 'https://deathrun3d.com'                                           },
  { id:'tinyfishing',     title:'Tiny Fishing',             cat:'Simulation',  thumb: NT('tinyfishing.png'),            src: 'https://tinyfishing.com'                                          },
  { id:'templerun2',      title:'Temple Run 2',             cat:'Arcade',      thumb: NT('templerun2.png'),             src: 'https://www.crazygames.com/embed/temple-run-2'                    },
  { id:'timeshooter3',    title:'Time Shooter 3',           cat:'Action',      thumb: NT('timeshooter3.png'),           src: 'https://htmlxm.github.io/h/time-shooter-3'                        },
  { id:'helixjump',       title:'Helix Jump',               cat:'Arcade',      thumb: NT('helixjump.png'),              src: 'https://www.crazygames.com/embed/helix-jump'                      },
  { id:'fireboy',         title:'Fireboy & Watergirl',      cat:'Multiplayer', thumb: NT('fireboyandwatergirl.png'),    src: 'https://www.coolmathgames.com/0-fireboy-and-watergirl-in-the-forest-temple' },
  { id:'doodlejump',      title:'Doodle Jump',              cat:'Arcade',      thumb: NT('doodlejump.png'),             src: 'https://doodle-jump.io'                                           },
  { id:'cuttherope',      title:'Cut the Rope',             cat:'Arcade',      thumb: NT('cuttherope.png'),             src: 'https://www.crazygames.com/embed/cut-the-rope'                    },
  { id:'googfeud',        title:'Google Feud',              cat:'Arcade',      thumb: NT('googlefeud.png'),             src: 'https://googlefeud.com'                                           },
  { id:'granny',          title:'Granny',                   cat:'Horror',      thumb: NT('granny.png'),                 src: 'https://www.crazygames.com/embed/granny'                          },
  { id:'vex7',            title:'Vex 7',                    cat:'Arcade',      thumb: NT('vex7.png'),                   src: 'https://www.crazygames.com/embed/vex-7'                           },
  { id:'hanger2',         title:'Hanger 2',                 cat:'Arcade',      thumb: NT('hanger2.png'),                src: 'https://www.crazygames.com/embed/hanger-2'                        },
  { id:'coreball',        title:'Coreball',                 cat:'Arcade',      thumb: NT('coreball.png'),               src: 'https://www.crazygames.com/embed/core-ball'                       },
  { id:'justfall',        title:'JustFall.LOL',             cat:'Multiplayer', thumb: NT('justfall.lol.png'),           src: 'https://justfall.lol'                                             },
  { id:'snowballio',      title:'Snowball.io',              src: 'https://www.crazygames.com/embed/snowball-io',        cat:'Multiplayer', thumb: NT('snowball.io.png')                         },
  { id:'paperio2',        title:'Paper.io 2',               cat:'Multiplayer', thumb: NT('paper.io2.png'),              src: 'https://paper-io.com'                                             },
  { id:'holeio',          title:'Hole.io',                  cat:'Multiplayer', thumb: NT('hole.io.png'),                src: 'https://hole-io.com'                                              },
  { id:'survivorio',      title:'Survivor.io',              cat:'Action',      thumb: NT('survivorio.png'),             src: 'https://www.crazygames.com/embed/survivor-io'                     },
  { id:'madalin',         title:'Madalin Stunt Cars 2',     cat:'Racing',      thumb: NT('madalinstuntcars2.png'),      src: 'https://www.crazygames.com/embed/madalin-stunt-cars-2'            },
  { id:'plantsvszombies', title:'Plants vs Zombies',        cat:'Strategy',    thumb: NT('plantsvszombies.png'),        src: 'https://www.crazygames.com/embed/plants-vs-zombies'               },
  { id:'gladihoppers',    title:'Gladihoppers',             cat:'Action',      thumb: NT('gladihoppers.png'),           src: 'https://www.crazygames.com/embed/gladihoppers',          hot:true  },
  { id:'fridaynightfunkin',title:'Friday Night Funkin',     cat:'Arcade',      thumb: NT('fridaynightfunkin.png'),      src: 'https://www.crazygames.com/embed/friday-night-funkin',   hot:true  },
  { id:'gunspin',         title:'GunSpin',                  cat:'Arcade',      thumb: NT('gunspin.png'),                src: 'https://www.crazygames.com/embed/gunspin'                         },
  { id:'footballlegends', title:'Football Legends',         cat:'Sports',      thumb: NT('footballlegends.png'),        src: 'https://www.crazygames.com/embed/football-legends-2021'           },
  { id:'2048',            title:'2048',                     cat:'Arcade',      thumb: NT('2048.png'),                   src: 'https://play2048.co'                                              },
  { id:'bloxorz',         title:'Bloxorz',                  cat:'Arcade',      thumb: NT('bloxorz.png'),                src: 'https://www.crazygames.com/embed/bloxorz'                         },
  { id:'fancypants2',     title:'Fancy Pants Adventures 2', cat:'Action',      thumb: NT('fancypantsadventures2.png'),  src: 'https://www.crazygames.com/embed/fancy-pants-adventure-2'         },
  { id:'extremepamplona', title:'Extreme Pamplona',         cat:'Action',      thumb: NT('extremepamplona.png'),        src: 'https://www.crazygames.com/embed/extreme-pamplona'                },
  { id:'awesometanks2',   title:'Awesome Tanks 2',          cat:'Action',      thumb: NT('awesometanks2.png'),          src: 'https://www.crazygames.com/embed/awesome-tanks-2'                 },
  { id:'rugbyio',         title:'Rugby.io Ball Mayhem',     cat:'Sports',      thumb: NT('rugby.ioballmayhem.png'),     src: 'https://www.crazygames.com/embed/rugbyio-ball-mayhem'             },
  { id:'bottleflip3d',    title:'Bottle Flip 3D',           cat:'Arcade',      thumb: NT('bottleflip3d.png'),           src: 'https://www.crazygames.com/embed/bottle-flip-3d'                  },
  { id:'aquapark',        title:'Aquapark Slides',          cat:'Arcade',      thumb: NT('aquaparkslides.png'),         src: 'https://www.crazygames.com/embed/aquapark-io'                     },
  { id:'stickarchersbattle',title:'Stick Archers Battle',   cat:'Action',      thumb: NT('stickarchersbattle.png'),     src: 'https://www.crazygames.com/embed/stick-archers-battle'            },
  { id:'jetpackjoyride',  title:'Jetpack Joyride',          cat:'Arcade',      thumb: NT('jetpackjoyride.png'),         src: 'https://www.crazygames.com/embed/jetpack-joyride'                 },
  { id:'gravitysoccer',   title:'Gravity Soccer',           cat:'Sports',      thumb: NT('gravitysoccer.png'),          src: 'https://www.crazygames.com/embed/gravity-soccer-3'                },
  { id:'jacksmith',       title:'Jacksmith',                cat:'Simulation',  thumb: NT('jacksmith.png'),              src: 'https://www.crazygames.com/embed/jacksmith'                       },
  { id:'raftwars2',       title:'Raft Wars 2',              cat:'Action',      thumb: NT('raftwars2.png'),              src: 'https://www.crazygames.com/embed/raft-wars-2'                     },
  { id:'superstickmangolf',title:'Super Stickman Golf 3',   cat:'Sports',      thumb: NT('superstickmangolf3.png'),     src: 'https://www.crazygames.com/embed/super-stickman-golf-3'           },
  { id:'shoppingcart',    title:'Shopping Cart Hero 3',     cat:'Arcade',      thumb: NT('shoppingcarthero3.png'),      src: 'https://www.crazygames.com/embed/shopping-cart-hero-3'            },
  { id:'jellytruck',      title:'Jelly Truck',              cat:'Racing',      thumb: NT('jellytruck.png'),             src: 'https://www.crazygames.com/embed/jelly-truck'                     },
  { id:'sportsheadsfootball',title:'Sports Heads Football', cat:'Sports',      thumb: NT('sportsheadsfootball.png'),    src: 'https://www.crazygames.com/embed/sports-heads-football'           },
  { id:'idlebreakout',    title:'Idle Breakout',            cat:'Arcade',      thumb: NT('idlebreakout.png'),           src: 'https://koalabeast.com/idlebreakout/'                             },
  { id:'ageofwar',        title:'Age of War',               cat:'Strategy',    thumb: NT('ageofwar.png'),               src: 'https://www.crazygames.com/embed/age-of-war'                      },
  { id:'unfairmario',     title:'Unfair Mario',             cat:'Arcade',      thumb: NT('unfairmario.png'),            src: 'https://www.crazygames.com/embed/unfair-mario'                    },
  { id:'osu',             title:'osu!',                     cat:'Arcade',      thumb: NT('osu.png'),                    src: 'https://osu.ppy.sh/home'                                          },
  { id:'backrooms',       title:'Backrooms',                cat:'Horror',      thumb: NT('backrooms.png'),              src: 'https://www.crazygames.com/embed/the-backrooms-game-free-roam-horror'  },
  { id:'combatonline',    title:'Combat Online',            cat:'Action',      thumb: NT('combatonline.png'),           src: 'https://www.crazygames.com/embed/combat-online'                   },
  { id:'melonplayground', title:'Melon Playground',         cat:'Simulation',  thumb: NT('melonplayground.png'),        src: 'https://www.crazygames.com/embed/melon-playground'                },
  { id:'townscaper',      title:'Townscaper',               cat:'Simulation',  thumb: NT('townscaper.png'),             src: 'https://oskarstalberg.com/Townscaper/'                            },
  { id:'stumbleguys',     title:'Stumble Guys',             cat:'Multiplayer', thumb: NT('stumbleguys.png'),            src: 'https://www.crazygames.com/embed/stumble-guys'                    },
  { id:'fruitninja',      title:'Fruit Ninja',              cat:'Arcade',      thumb: NT('fruitninja.png'),             src: 'https://www.crazygames.com/embed/fruit-ninja'                     },
  { id:'rocketbotroyale', title:'Rocket Bot Royale',        cat:'Action',      thumb: NT('rocketbotroyale.png'),        src: 'https://rocketbotroyale.winterpixel.io/'                          },
  { id:'pokemongame',     title:'Pokémon',                  cat:'Adventure',   thumb: NT('pokemon.png'),                src: 'https://www.crazygames.com/embed/pokemon-go'                      },
  { id:'dadish',          title:'Dadish',                   cat:'Adventure',   thumb: NT('dadish.png'),                 src: 'https://www.crazygames.com/embed/dadish'                          },
  { id:'deepestsword',    title:'Deepest Sword',            cat:'Adventure',   thumb: NT('deepestsword.png'),           src: 'https://www.crazygames.com/embed/deepest-sword'                   },
  { id:'badtimesimulator',title:'Bad Time Simulator',       cat:'Action',      thumb: NT('badtimesimulator.png'),       src: 'https://jcw87.github.io/c2-sans-fight/'                           },
  { id:'dogeminer',       title:'Doge Miner',               cat:'Simulation',  thumb: NT('dogeminer.png'),              src: 'https://dogeminer.se'                                             },
  { id:'csgo',            title:'CS:GO Clicker',            cat:'Simulation',  thumb: NT('csgoclicker.png'),            src: 'https://www.crazygames.com/embed/csgo-clicker'                    },
  { id:'tabs',            title:'T.A.B.S',                  cat:'Simulation',  thumb: NT('totallyaccuratebattlesimulator.png'), src: 'https://www.crazygames.com/embed/totally-accurate-battle-simulator' },
  { id:'windows98',       title:'Windows 98',               cat:'Simulation',  thumb: NT('windows98.png'),              src: 'https://98.js.org'                                                },
  { id:'circloo',         title:'circloO',                  cat:'Arcade',      thumb: NT('circloO.png'),                src: 'https://www.crazygames.com/embed/circloo'                         },
  { id:'eaglercraft',     title:'Eaglercraft',              cat:'Adventure',   thumb: NT('eaglercraft.png'),            src: 'https://eaglercraft.com/mc/1.8.8/'                                },
  { id:'eaglercraftx',    title:'EaglercraftX',             cat:'Adventure',   thumb: NT('eaglercraftx.png'),           src: 'https://eaglercraftx.com/mc/1.8/'                                 },
  { id:'ducklife4',       title:'Duck Life 4',              cat:'Simulation',  thumb: NT('ducklife4.png'),              src: 'https://www.crazygames.com/embed/duck-life-4'                     },
  { id:'slope2',          title:'Slope 2',                  cat:'Arcade',      thumb: NT('slope2.png'),                 src: 'https://slope2.io'                                                },
  { id:'doom2',           title:'Doom 2',                   cat:'Action',      thumb: NT('doom2.png'),                  src: 'https://silentspacemarine.com/doom2/'                             },
  { id:'badicecream',     title:'Bad Ice Cream',            cat:'Arcade',      thumb: NT('badicecream.png'),            src: 'https://www.crazygames.com/embed/bad-ice-cream'                   },
  { id:'angrysharks',     title:'Angry Sharks',             cat:'Action',      thumb: NT('angrysharks.png'),            src: 'https://www.crazygames.com/embed/angry-sharks'                    },
  { id:'spyhighway',      title:'Spy Highway',              cat:'Racing',      thumb: NT('spyhighway.png'),             src: 'https://www.crazygames.com/embed/spy-highway'                     },
  { id:'agesofconflict',  title:'Ages of Conflict',         cat:'Strategy',    thumb: NT('agesofconflict.png'),         src: 'https://www.crazygames.com/embed/ages-of-conflict'                },
  { id:'trafficjam3d',    title:'Traffic Jam 3D',           cat:'Racing',      thumb: NT('trafficjam3d.png'),           src: 'https://www.crazygames.com/embed/traffic-jam-3d'                  },
  { id:'murderbethking',  title:'Murder: Be The King',      cat:'Strategy',    thumb: NT('murderbetheking.png'),        src: 'https://www.crazygames.com/embed/murder'                          },
  { id:'knifehit',        title:'Knife Hit',                cat:'Arcade',      thumb: NT('knifehit.png'),               src: 'https://www.crazygames.com/embed/knife-hit'                       },
  { id:'froggysbattle',   title:"Froggy's Battle",          cat:'Action',      thumb: NT('froggysbattle.png'),          src: 'https://www.crazygames.com/embed/froggys-battle'                  },
  { id:'drunkenboxing2',  title:'Drunken Boxing 2',         cat:'Sports',      thumb: NT('drunkenboxing2.png'),         src: 'https://www.crazygames.com/embed/drunken-boxing-2'                },
  { id:'stickduelbattle', title:'Stick Duel Battle',        cat:'Action',      thumb: NT('stickduelbattle.png'),        src: 'https://www.crazygames.com/embed/stick-duel-battle'               },
  { id:'sausageflip',     title:'Sausage Flip',             cat:'Arcade',      thumb: NT('sausageflip.png'),            src: 'https://www.crazygames.com/embed/sausage-flip'                    },
  { id:'basket-n-ball',   title:'Basket & Ball',            cat:'Sports',      thumb: NT('basketandball.png'),          src: 'https://www.crazygames.com/embed/basket-and-ball'                 },
  { id:'learntofly3',     title:'Learn to Fly 3',           cat:'Arcade',      thumb: NT('learntofly3.png'),            src: 'https://www.crazygames.com/embed/learn-to-fly-3'                  },
  { id:'tacticalassassin',title:'Tactical Assassin 2',      cat:'Action',      thumb: NT('tacticalassassin2.png'),      src: 'https://www.crazygames.com/embed/tactical-assassin-2'             },
  { id:'aceattorney',     title:'Ace Attorney',             cat:'Adventure',   thumb: NT('aceattorney.png'),            src: 'https://www.crazygames.com/embed/ace-attorney-online'             },
  { id:'bobtherobber',    title:'Bob the Robber',           cat:'Adventure',   thumb: NT('bobtherobber.png'),           src: 'https://www.crazygames.com/embed/bob-the-robber'                  },
  { id:'riddleschool',    title:'Riddle School',            cat:'Adventure',   thumb: NT('riddleschool.png'),           src: 'https://www.crazygames.com/embed/riddle-school'                   },
  { id:'riddle2',         title:'Riddle School 2',          cat:'Adventure',   thumb: NT('riddleschool2.png'),          src: 'https://www.crazygames.com/embed/riddle-school-2'                 },
  { id:'riddle3',         title:'Riddle School 3',          cat:'Adventure',   thumb: NT('riddleschool3.png'),          src: 'https://www.crazygames.com/embed/riddle-school-3'                 },
  { id:'infiltrating',    title:'Infiltrating the Airship', cat:'Adventure',   thumb: NT('infiltratingtheairship.png'), src: 'https://www.crazygames.com/embed/infiltrating-the-airship'        },
  { id:'bloons3',         title:'Bloons TD 3',              cat:'Strategy',    thumb: NT('bloonstd3.png'),              src: 'https://www.crazygames.com/embed/bloons-tower-defense-3'          },
  { id:'worldshardest',   title:"The World's Hardest Game", cat:'Arcade',      thumb: NT('theworldshardestgame.png'),   src: 'https://www.crazygames.com/embed/the-worlds-hardest-game'         },
  { id:'impossiblequiz',  title:'The Impossible Quiz',      cat:'Arcade',      thumb: NT('theimpossiblequiz.png'),      src: 'https://www.crazygames.com/embed/the-impossible-quiz'             },
  { id:'ninjavsevilcorp', title:'Ninja vs Evil Corp',       cat:'Action',      thumb: NT('ninjavsevilcorp.png'),        src: 'https://www.crazygames.com/embed/ninja-vs-evil-corp'              },
  { id:'rocketleague2d',  title:'Rocket League 2D',         cat:'Sports',      thumb: NT('rocketleague2d.png'),         src: 'https://www.crazygames.com/embed/rocket-league-2d'                },
  { id:'rocketsoccerderby',title:'Rocket Soccer Derby',     cat:'Sports',      thumb: NT('rocketsoccerderby.png'),      src: 'https://www.crazygames.com/embed/rocket-soccer-derby'             },
  { id:'hobo',            title:'Hobo',                     cat:'Action',      thumb: NT('hobo.png'),                   src: 'https://www.crazygames.com/embed/hobo'                            },
  { id:'hobo2',           title:'Hobo 2',                   cat:'Action',      thumb: NT('hobo2.png'),                  src: 'https://www.crazygames.com/embed/hobo-2-wanted'                   },
  { id:'hobo3',           title:'Hobo 3',                   cat:'Action',      thumb: NT('hobo3.png'),                  src: 'https://www.crazygames.com/embed/hobo-3-wanted'                   },
  { id:'hobo4',           title:'Hobo 4',                   cat:'Action',      thumb: NT('hobo4.png'),                  src: 'https://www.crazygames.com/embed/hobo-4-total-war'                },
  { id:'hobo5',           title:'Hobo 5',                   cat:'Action',      thumb: NT('hobo5.png'),                  src: 'https://www.crazygames.com/embed/hobo-5-wanted'                   },
  { id:'hobo6',           title:'Hobo 6 Hell',              cat:'Action',      thumb: NT('hobo6.png'),                  src: 'https://www.crazygames.com/embed/hobo-6-hell'                     },
  { id:'hobo7',           title:'Hobo 7 Heaven',            cat:'Action',      thumb: NT('hobo7.png'),                  src: 'https://www.crazygames.com/embed/hobo-7-heaven'                   },
  { id:'eggycar',         title:'Eggy Car',                 cat:'Racing',      thumb: NT('eggycar.png'),                src: 'https://www.crazygames.com/embed/eggy-car',             hot:true  },
  { id:'noobsteve',       title:'Noob Steve Parkour',       cat:'Adventure',   thumb: NT('noobsteveparkour.png'),       src: 'https://www.crazygames.com/embed/noob-steve-parkour'              },
  { id:'burgerbounty',    title:'Burger Bounty',            cat:'Simulation',  thumb: NT('burgerbounty.png'),           src: 'https://www.crazygames.com/embed/burger-bounty'                   },
  { id:'spacething',      title:'Space Thing',              cat:'Action',      thumb: NT('spacething.png'),             src: 'https://www.crazygames.com/embed/space-thing'                     },
  { id:'bankrobbery',     title:'Bank Robbery',             cat:'Action',      thumb: NT('bankrobbery.png'),            src: 'https://www.crazygames.com/embed/bank-robbery'                    },
  { id:'pixelsmashduel',  title:'Pixel Smash Duel',         cat:'Action',      thumb: NT('pixelsmashduel.png'),         src: 'https://www.crazygames.com/embed/pixel-smash-duel'                },
  { id:'xtrial',          title:'X-Trial Racing',           cat:'Racing',      thumb: NT('xtrialracing.png'),           src: 'https://www.crazygames.com/embed/x-trial-racing'                  },
  { id:'slimerushtd',     title:'Slime Rush TD',            cat:'Strategy',    thumb: NT('slimerushtd.png'),            src: 'https://www.crazygames.com/embed/slime-rush-td'                   },
  { id:'gravityfalls',    title:'Gravity Falls TBTF',       cat:'Adventure',   thumb: NT('gravityfalls.png'),           src: 'https://www.crazygames.com/embed/gravity-falls-rumble'            },
  { id:'fryingnemo',      title:'Frying Nemo',              cat:'Arcade',      thumb: NT('fryingnemo.png'),             src: 'https://www.crazygames.com/embed/frying-nemo'                     },
  { id:'boxingphysics2',  title:'Boxing Physics 2',         cat:'Sports',      thumb: NT('boxingphysics2.png'),         src: 'https://www.crazygames.com/embed/boxing-physics-2'                },
  { id:'douchebagworkout',title:'Douchebag Workout 2',      cat:'Simulation',  thumb: NT('douchebagworkout2.png'),      src: 'https://www.crazygames.com/embed/douchebag-workout-2'             },
  { id:'stickduelmed',    title:'Stick Duel: Medieval Wars',cat:'Action',      thumb: NT('stickduelmedievalwars.png'),  src: 'https://www.crazygames.com/embed/stick-duel-medieval-wars'        },
  { id:'papalouie2',      title:"Papa Louie 2: WBA",        cat:'Adventure',   thumb: NT('papalouie2.png'),             src: 'https://www.crazygames.com/embed/papa-louie-2-when-burgers-attack' },
  { id:'myrustysubmarine',title:'My Rusty Submarine',       cat:'Adventure',   thumb: NT('myrustysubmarine.png'),       src: 'https://www.crazygames.com/embed/my-rusty-submarine'              },
  { id:'defendthetank',   title:'Defend the Tank',          cat:'Strategy',    thumb: NT('defendthetank.png'),          src: 'https://www.crazygames.com/embed/defend-the-tank'                 },
  { id:'60sburgerrun',    title:'60s Burger Run',           cat:'Arcade',      thumb: NT('60sburgerrun.png'),           src: 'https://www.crazygames.com/embed/60s-burger-run'                  },
  { id:'santyishome',     title:'Santy Is Home',            cat:'Horror',      thumb: NT('santyishome.png'),            src: 'https://www.crazygames.com/embed/santy-is-home'                   },
  { id:'justoneboss',     title:'Just One Boss',            cat:'Action',      thumb: NT('justoneboss.png'),            src: 'https://www.crazygames.com/embed/just-one-boss'                   },
  { id:'evilglitch',      title:'Evil Glitch',              cat:'Action',      thumb: NT('evilglitch.png'),             src: 'https://www.crazygames.com/embed/evil-glitch'                     },
  { id:'andeverything',   title:'& Everything Started to Fall', cat:'Arcade',  thumb: NT('andeverythingstartedtofall.png'), src: 'https://www.crazygames.com/embed/and-everything-started-to-fall' },
  { id:'doctoracorn2',    title:'Doctor Acorn 2',           cat:'Arcade',      thumb: NT('doctoracorn2.png'),           src: 'https://www.crazygames.com/embed/doctor-acorn-2'                  },
  { id:'policechasedrifter',title:'Police Chase Drifter',   cat:'Racing',      thumb: NT('policechasedrifter.png'),     src: 'https://www.crazygames.com/embed/police-chase-drifter'            },
  { id:'mysub',           title:'My Rusty Submarine',       cat:'Adventure',   thumb: NT('myrustysubmarine.png'),       src: 'https://www.crazygames.com/embed/my-rusty-submarine'              },
];
